//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgpManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NgpdbmsEntities : DbContext
    {
        public NgpdbmsEntities()
            : base("name=NgpdbmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ngp_contract> ngp_contract { get; set; }
        public virtual DbSet<ngp_contractor> ngp_contractor { get; set; }
        public virtual DbSet<ngp_dropdown> ngp_dropdown { get; set; }
        public virtual DbSet<ngp_history> ngp_history { get; set; }
        public virtual DbSet<ngp_payment> ngp_payment { get; set; }
        public virtual DbSet<ngp_projects> ngp_projects { get; set; }
        public virtual DbSet<NgpBarangay> NgpBarangays { get; set; }
        public virtual DbSet<NgplocationBarangay> NgplocationBarangays { get; set; }
        public virtual DbSet<NgplocationMunicipality> NgplocationMunicipalities { get; set; }
        public virtual DbSet<NgpLogsContract> NgpLogsContracts { get; set; }
        public virtual DbSet<NgpLogsContractor> NgpLogsContractors { get; set; }
        public virtual DbSet<NgpLogsPayment> NgpLogsPayments { get; set; }
        public virtual DbSet<NgpLogsProject> NgpLogsProjects { get; set; }
        public virtual DbSet<NgpLogsSched> NgpLogsScheds { get; set; }
        public virtual DbSet<NgpLogsUserAccount> NgpLogsUserAccounts { get; set; }
        public virtual DbSet<NgpMaintenanceMode> NgpMaintenanceModes { get; set; }
        public virtual DbSet<NgpMunicipality> NgpMunicipalities { get; set; }
        public virtual DbSet<NgpRole> NgpRoles { get; set; }
        public virtual DbSet<NgpUpload> NgpUploads { get; set; }
        public virtual DbSet<NgpUser> NgpUsers { get; set; }
        public virtual DbSet<NgpYear> NgpYears { get; set; }
    }
}
