//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgpManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngp_projects
    {
        public int projectID { get; set; }
        public string site_code { get; set; }
        public Nullable<int> location_municipality { get; set; }
        public Nullable<int> location_barangay { get; set; }
        public string area { get; set; }
        public string year_form { get; set; }
        public string penro { get; set; }
        public string cenro { get; set; }
        public string region { get; set; }
        public Nullable<int> dropdownID { get; set; }
    
        public virtual ngp_dropdown ngp_dropdown { get; set; }
        public virtual NgpBarangay NgpBarangay { get; set; }
        public virtual NgpMunicipality NgpMunicipality { get; set; }
    }
}
